In [1]:
import torch

In [3]:
x = torch.Tensor([2, 3])
y = torch.Tensor([5, 1])

print(x*y)

tensor([10.,  3.])


In [4]:
x = torch.zeros([2, 5])    # zeros
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [5]:
x.shape

torch.Size([2, 5])

In [6]:
y = torch.rand([2, 5])    # random
y

tensor([[0.0842, 0.2874, 0.9112, 0.0010, 0.6860],
        [0.6305, 0.9551, 0.4878, 0.3246, 0.9051]])

In [7]:
y = y.view([1, 10])    # reshape
print(y)

tensor([[0.0842, 0.2874, 0.9112, 0.0010, 0.6860, 0.6305, 0.9551, 0.4878, 0.3246,
         0.9051]])
